### ISSUE TITLE
How do I know the example scene is working or not.

### ISSUE THREAD

**Issue by jin-archipin** [Funnyguy77/PocketSphinxUnityDemo#1]
Thank you for this amazing work!
However I'm having trouble playing ExampleScene.
I figured out I need to press space to record, but I don't know what's happening and how do I know the output? The log is only says started and stopped like below.

![image](https://user-images.githubusercontent.com/58724408/73916033-f1deeb00-48ff-11ea-94eb-f5125a6efb52.png)

**Comment by b29b** [comment]
its not detecting any microphone on windows, how did you get it to work?

**Comment by Funnyguy77** [comment]
Ah, sorry about that! I should have been more clear when documenting this. 

Here's what *should* happen:
1: Press spacebar -> microphone starts recording.
2: Speak the phrase prompted.
3: If it's recognized it should say "Keyphrase detected!" in the scene. (I don't think it actually outputs anything in the log, I will need to change this...) 

In the bottom right of your screen it should also say which microphone is in use. Is that a valid microphone?

**Comment by jin-archipin** [comment]
My mic is working on other projects well. and this demo also detects my mic.

![image](https://user-images.githubusercontent.com/58724408/73992428-7e39ee00-4992-11ea-9d83-c50f145aabc9.png)

btw, your profile picture's background looks familiar to me lol

**Comment by jin-archipin** [comment]
I found that d.Hyp() below is returning null

![image](https://user-images.githubusercontent.com/58724408/73992931-079df000-4994-11ea-815c-1c46412e5565.png)

**Comment by Funnyguy77** [comment]
What's the size of your language model (StreamingAssets/en-us.tar) file? It should be around 9.43 MB. I've had a similar issue this morning where I wasn't able to decompress my language model because when I downloaded from Git it didn't download the whole file.  If you can't decompress the model (because the file is empty) you're not able to initialize the decoder, causing it to be null. 

Also are you getting any errors in the console?

**Comment by jin-archipin** [comment]
It is 9.43MB. Console is exactly same as above. There is no error at all.

**Comment by Funnyguy77** [comment]
Just did a test on a new machine and cloned from the repo and was able to get it working.

For fun, can you add a Debug.Log() inside of the if statement you posted? Just have it output something saying "Phrase detected". I think your project may actually be functioning, but you're not seeing it recognize anything. Currently it changes the text on the screen for roughly a second. 

Try that and see if it outputs anything. Make sure you press space -> say "this is a test" -> then press space again to stop the recording.

Edit: Just saw your post about my profile photo. Are you from Korea? My photo was from a recent trip to Seoul. :D

**Comment by jin-archipin** [comment]
Hey Sorry I was super busy to try this. I'll try debug it asap after I finish current works.
Yes, I live in seoul. haha hope you enjoyed my city.

**Comment by Funnyguy77** [comment]
No worries! I apologize for closing the issue. I'm reopening it. :)

**Comment by jin-archipin** [comment]
FYI, I'm not dead yet! haha
I'm working at home due to this corona outbreaks, but I don't have my mic in my home...
Sorry for long delaying

**Comment by chubillkelvin** [comment]
Sharing my experience here:

1. Suggest to use git to clone the repo since it contains large file storage. It created a problem for me when I used zip to download and open the project.

2. Make sure if you have changed the phrase to be detected, they are in lowercase letters. As the original comments suggested, they are case-sensitive.

3. If `d.Hyp()` is returning null constantly, this might be because of pronunciation or tolerance. I figured this when I tried using words like `spark` or `water` . Turns out they have different pronunciation in British / American accents. The default language model is `en-us` so you might want to check out the American pronunciation. If this didn't work out, try changing the tolerance value - @Funnyguy77 did a very amazing job in commenting and pin-pointing these value in the example script.

**Comment by jin-archipin** [comment]
@RageBill Thank you for your tips!
I will keep those in my mind

**Comment by Funnyguy77** [comment]
@RageBill Great suggestions, and thank you!
@jin-archipin No worries, and please stay safe!

**Comment by jin-archipin** [comment]
![image](https://user-images.githubusercontent.com/58724408/76061424-d599a100-5fc6-11ea-87f0-2e9f8d8b280f.png)
I set kws threshold to 1e-1.
I tried fast, slowly or clearly many times, but d.Hyp() is always null
My accent is close to american accent btw. I worked in the U.S. Army for 2 years

**Comment by jin-archipin** [comment]
Nvm It works when I set the threshold to 1e-50.

Thank you @Funnyguy77 and @RageBill
