### ISSUE TITLE
Splitting audio files for continuous recognition 

### ISSUE THREAD

**Issue by KiritoAsunaYui2022** [Funnyguy77/PocketSphinxUnityDemo#17]
In a previous post,  [you mentioned](https://github.com/Funnyguy77/PocketSphinxUnityDemo/issues/2) it is possible to have a continuous recognition by splitting the audio whenever you start and stop speaking. I am going to swallow my pride and say I don't know how to do that haha. In the script SphinxExample I thought it would be ok to put the 
`if (!Microphone.IsRecording(mic.Name))
            {
                mic.BeginRecording();
            }` 
inside the private IEnumerator Start() function (or somewhere else) and put the `mic.EndRecording();` 

right after or somewhere inside 

`if (d.Hyp() != null)
        {
            // Fire our event.
            if (OnSpeechRecognized != null)
            {
                OnSpeechRecognized.Invoke(d.Hyp().Hypstr);
                //mic.EndRecording();
                //print("RECOGNIZED"); 
            }

            // Stop the decoder.
            d.EndUtt();
            // Start the decoder again.
            d.StartUtt();
        }`
 and call it a day or hope for it to magically happen. Except for now I just have the IF statement where when you press the Space key it just calls the mic.EndRecording();. I soon realized that it destroys the Audio clip after the first recognition. I thought this would work, but it didn't haha. 

TDLR: I tried I cheap way for what I thought would work for continuous recognition but it didn't. As you have said before, there isn't a ton of documentation for pocketsphinx, so right now you're pretty much it to help me figure this (and probably more problems) out. Help me Obi-Wan Kenobi, you're my only hope.

**Comment by Funnyguy77** [comment]
Hi there! 

To be 100% honest with you, I haven't had a ton of time to respond to issues on this repo lately. But the Obi-Wan Kenobi quote made me laugh, so I figured I could at least give you a response. 

If you wanted to setup continuous recognition you will need to have the microphone record at all times. At the same time however, you need to feed information to PocketSphinx. In the past I've tested using the live microphone input with Sphinx, but my accuracy was terrible. Mostly due to Sphinx attempting to interpret my language to early. 

What does that mean? Well, instead of passing the live-feed into Sphinx you will need to create clips, which are then passed into Sphinx. (The demo does this now, but only after a user presses a key.)

I've been very busy lately and haven't been able to create an example showing this sort of functionality with an always-on microphone. 

If you're going to actively split your microphone into recording clips, my first thought would be to look at your input volume. When the input volume is high, you know a user is speaking. Otherwise, they're silent and the volume will be low. 

I found a really clever solution here on the Unity Forms that might help. (Shoutout to User: atomtwist) His solution is about halfway down the page. [[Link]](https://forum.unity.com/threads/check-current-microphone-input-volume.133501/) (Disclaimer: This solution is untested, you will need to experiment with it yourself.)

Once you have your input volume, you can simply create new audio clips when a user finishes speaking.

Here's an example:
**1.** User begins speaking. (Input volume is high.)
**2.** User finishes speaking. (Input volume returns to a low value. It probably won't ever be 0 since there's most likely to be ambient noise in the room.)
**3.** You create an audio clip using the data you've already been recording with your microphone.
**4.** Pass the audio clip into Sphinx.

Hopefully this information helps with your integration of the demo project!

**Comment by Funnyguy77** [comment]
Closing this issue. Please reopen if you have other questions!
