### ISSUE TITLE
Building for Oculus Quest

### ISSUE THREAD

**Issue by geezlouisee** [Funnyguy77/PocketSphinxUnityDemo#19]
Hi all, managed to get the project up and running in the Unity Editor but unfortunately, I'm unable to get it working on the Oculus Quest. One potential issue I could think of would be I am not building the project properly for Oculus Quest(?) Not really sure if what I tried is correct, but what I did was:
1. Imported Oculus Integration v17
2. Switch platform to Android
2. For `player settings > XR settings` : checked Virtual Reality Supported
3. For `player settings > other settings`
![image](https://user-images.githubusercontent.com/39251616/85519502-2f84ac00-b634-11ea-8103-cf311a921a27.png)
4. I also added a OVRPlayerController in my scene... (as now instead of using spacebar to trigger the recording, I want to use one of the controller buttons instead)

On that note, just curious how would one usually go in building a project to deploy to Oculus Quest? 
(since there were no specific instructions given in the `README.md` file)

Thanks in advance!

**Comment by Funnyguy77** [comment]
Hi there! Thanks so much for checking out my repo!

I'm going to take a look at this issue later this afternoon and I'll update once I have an answer. :) Just wanted to acknowledge that I have seen this issue and am taking a look at it.

**Comment by Funnyguy77** [comment]
Hi again! I took some time today to build a version of the project for Oculus Quest and was able to get it working! 
_(Tested in Unity 2019.4.0f1 LTS)_

Like you mentioned before I think you're just missing a small step when setting up the project. (Most likely not requesting microphone permission or forgetting to create the AndroidManifest.xml file)

Here's my step-by-step process for how I setup the Oculus Quest project:
**1.** Set project platform to Android.
**2.** Import Oculus Integration.
**3.** Add Oculus SDK in XR Settings. (Project Settings -> Player -> XR Settings) Make sure to enable V2 Signing.
**4.** Setup your Oculus Application ID. (Oculus -> Tools -> OVR Platform Tool) If it's already there, you can ignore this step.
**5. [IMPORTANT]** Make sure you request microphone permission!

```
// SAMPLE CODE FOR REQUESTING MICROPHONE PERMISSION.

using UnityEngine;
#if PLATFORM_ANDROID
using UnityEngine.Android;
#endif

public class MicrophonePermission : MonoBehaviour
{
    private void Start()
    {
#if PLATFORM_ANDROID
        if (!Permission.HasUserAuthorizedPermission(Permission.Microphone))
        {
            Permission.RequestUserPermission(Permission.Microphone);
        }
#endif
    }
}
```
**6.** Update the Sphinx Example script to use the Quest controller buttons instead of spacebar.
```
private void Update()
    {
        // SAMPLE CODE FOR USING OCULUS QUEST CONTROLLERS.
        // "A" button on the Oculus Quest controller.
        if (OVRInput.GetDown(OVRInput.Button.One)) 
        {
            if(!Microphone.IsRecording(mic.Name))
            {
                mic.BeginRecording();
            }
            else
            {
                mic.EndRecording();
            }
        }
    }
```
**7. [IMPORTANT]** Make sure to create a store manifest. (Oculus -> Tools -> Create store compatible AndroidManifest.xml)
**8.** Build & copy to your Quest!

I will need to go ahead and update the `README.md` file to include these steps. Thank you for the suggestion. 

Additionally, if you would like a copy of my project that I setup this afternoon, I would be happy to provide a download link! :)

**Comment by geezlouisee** [comment]
Hi @Funnyguy77 , thank you so much for your prompt reply!

I forgot to mention that I was also trying to test multiple keyword detection when I tried to build the project previously.
Just wanted to ask if this will also work if I have multiple keywords (phrases) in `keywords.txt`?

I've listed more details about the problem I faced in another issue thread (#15).

Will also appreciate it if you could provide a download link of a copy of your project too :)

Thanks for your help again and will update here when I've tried these steps out!

**Comment by Funnyguy77** [comment]
No problem, happy to help!

In regards to your question about using a `keywords.txt` file. I haven't tested anything, but in theory yes this setup should work for loading that text file from the StreamingAssets folder. 

I do see the other issue you faced on thread #15. My initial thought as to why the project won't open is either you haven't assigned an application ID in your OVR Platform Tool. Or, you've not generated a store compatible `AndroidManifest.xml`. I've seen similar issues in my own testing. Hopefully that helps to resolve your issue. 

Here's a link to the sample project I setup. [[Link]](https://www.dropbox.com/s/snh8g6wrq2mzvo1/PocketSphinxUnity_Quest.zip?dl=0) The project also includes a _Builds folder with a pre-built APK that I've tested on my Oculus Quest. The project was built in Unity 2019.4.0f1 LTS, but it should work on 2019.3 as well.

Let me know if you have any other questions!

**Comment by Funnyguy77** [comment]
Closing this issue. Please re-open if you continue to encounter issues!
