### ISSUE TITLE
Latency in detecting the phrases

### ISSUE THREAD

**Issue by chubillkelvin** [Funnyguy77/PocketSphinxUnityDemo#2]
First of all, thank you so much for the demo project!

I was exactly needing an offline voice recognition package on my Oculus Quest like you do, this was amazing!

I have tested out the demo project on macOS Catalina with Unity v2019.2, and it worked out fine.

However, I have some "latency" in detecting the phrases - I was only able to get the phrase detected only if I:

1) start speaking after the recording starts for a short while (~0.5s)

2) ends recording after a short while after I finished speaking (~0.5s)

I was hoping to build a game with spoken spells to cast magic, and I was testing out with the phrase "fire". This latency really does compromise the experience. Wonder if there is any way I could improve this?

I have tried changing the -kws_threshold to make it more tolerant, but the above issue still seems to persist.

Thank you!

**Comment by Funnyguy77** [comment]
I'm glad that the demo project was able to be of some use for you! 

I would suggest a few things to improve your latency:

1. Migrate to a custom language model. I've found that when you search through a large dictionary such as the EN-US model, phrases can take longer to recognize.  

2. Continuously listen to your microphone and split the audio file whenever you start & stop speaking. 

3. Multi-threading.  I've had limited success with this in my personal tests, but if you find that your slowing your main thread, try moving the Sphinx recognition to another thread.

I think you will probably have the most success with either trying a smaller dictionary, or migrating to a smaller language model. 

Here's a link to a few other models you can try: 
https://sourceforge.net/projects/cmusphinx/files/

I'll try to also update the demo in the near future to include an example for using language model based recognition instead of keyphrase based.

**Comment by chubillkelvin** [comment]
Thanks for the advice! I will try to play around with your suggestions and see if I find any improvements in the performance!

**Comment by chubillkelvin** [comment]
I was trying to implement multiple key word search here.

Instead of recognising a single phrase, is there a way to make it find and recognise, say, one of the phrases in an array? Do I have to just simply loop the array to try recognising each phrase until one is found or it is end of array? Is there a better and more efficient way to do this?

Thank you for your help in advance!

**Comment by Funnyguy77** [comment]
Great question! 

Yes, it is possible and quite simple to recognize multiple keywords. 

```
// Instead of using this to set our keyword search.
c.SetString("-keyphrase", keyphrase);

// Use this instead. Where our path leads to a text file.
c.SetString("-kws", YOUR_FILE_PATH_HERE);
```

Here's what an example keyphrase text file would look like. It's important to note that your phrases are separated line-by-line.

```
hello world
this is an example sentence
somebody once told me
the world was gonna role me
```


I'll have to add this to the TODO list for examples. In the meantime, I hope this helps!

**Comment by chubillkelvin** [comment]
I have tested it and it works! Thank you so much for the help!

It might be useful for someone to know that `d.Hyp().Hypstr` would be useful for those who wonder where to find the phrase being recognized here.

**Comment by Funnyguy77** [comment]
Closing this issue, appears to be resolved. Please re-open if you continue to encounter issues.
