### ISSUE TITLE
Delay in Spotting LM (Oculus Quest 2)

### ISSUE THREAD

**Issue by menandro** [Funnyguy77/PocketSphinxUnityDemo#22]
Thank you for sharing your work. I got this to work on Oculus Quest 2. However, is it normal that there's a delay in "finding" the phrases? I tried putting some processes (ProcessAudio) in coroutines, but it still eating up the main thread especially when the audio recorded is long.

**Comment by Funnyguy77** [comment]
No problem. Thanks for checking out the repo.  😄 

You will see a performance spike when using long recordings. That's due to Sphinx needing to process a larger audio file. Ideally you would want to keep your audio recordings short.

In terms of performance, you can put Sphinx on another thread and keep your main thread clean. I've experimented with this in the past, and was able to get it working. During my tests I did notice a significant increase in performance on the Quest (v1). I haven't gotten a chance to use the Oculus Quest 2 though, so you might need to do your own tests.

**Comment by menandro** [comment]
Thanks. I moved the d.ProcessRaw(...) into an async function, and the delay is gone.
