### ISSUE TITLE
Project Crashes With Language Model

### ISSUE THREAD

**Issue by chubillkelvin** [Funnyguy77/PocketSphinxUnityDemo#3]
Thank for adding the extra feature here! I couldn't wait to test it out today.

I have downloaded and opened a new project from your new commits. 

When I was using the KWS, it worked out just fine. However, the project crashed when I tried the following to test out using a language model:
```
//SetupDecoderKWS();
SetupDecoderLM();
```

It happens when I start and then stop the recording. Once the recording is stopped, the project immediately crashes. I have been able to consistently reproduce this. And the project worked out fine with KWS instead of LM.

Hope you can point me to some way to fix this! Thanks!

**Comment by Funnyguy77** [comment]
Ah yes, this is the wonder of debugging with Sphinx. Essentially, whenever the decoder has a problem it simply crashes Unity. 

Just went ahead and cloned the repo on another local machine and wasn't encountering any crashing. Are you downloading the project as a zip or cloning the repo? If you're downloading, instead try cloning a fresh copy of the project on your machine.

I've found that when you download the language model from GitHub as a zip it's not included. (I assume this is because it's stored in Git LFS) You can confirm this by checking the actual file-size of the model in your project. (It should ~36 Mb)

Edit: To better explain, my theory is that Sphinx is trying to access an empty language model, which either doesn't include the .lm.bin file or is empty.

**Comment by chubillkelvin** [comment]
Wow, this totally fixed my problem!

I was downloading the project with zip, and apparently this causes some files to go missing.

Once I use `git clone` (with git-lfs installed), this fixed my problem! Thank you!

**Comment by Funnyguy77** [comment]
No problem! Glad it was resolved. 👍
